name: 'vslam_localizer'

algorithm:
  _target_: pyrobot.algorithms.base_localizer_impl.vslam_localizer.VSLAMLocalizer

robot_labels: ['locobot']

conf:
  MAP_IMG_DIR: /home/fair-pitt/.ros/Imgs
  ROSTOPIC_CAMERA_POSE: "/orb_slam2_rgbd/slam/camera_pose"
  ROSTOPIC_CAMERA_TRAJ: "/orb_slam2_rgbd/slam/camera_traj"
  RGB_CAMERA_CENTER_FRAME: "/camera_color_optical_frame"
  OCCUPANCY_MAP_RATE: 0.5
  Z_MIN_TRESHOLD_OCC_MAP: 0.1
  Z_MAX_TRESHOLD_OCC_MAP: 0.8
