version: 2.1

jobs:
  melodic_install_ubuntu_18:
    resource_class: xlarge
    docker:
      - image: ros:melodic-robot-bionic

    steps:
      - checkout            
      - run:
          name: Installer Python3
          command: |
            sudo apt-get install -y python-rosdep

            sudo apt-get update && sudo apt-get -y upgrade && sudo apt-get -y dist-upgrade
            cd ~/project/
            chmod +x install_all.sh
            ./install_all.sh -t sim_only -l interbotix

      - run:
          name: Run tests in Python3
          command: |
            source ~/.bashrc
            source /opt/ros/$ROS_DISTRO/setup.bash
            source ~/low_cost_ws/devel/setup.bash
            source ~/pyenv_pyrobot_python3/bin/activate
            source ~/pyrobot_catkin_ws/devel/setup.bash
            cd ~/project/tests/
            chmod +x circleci_tests.sh
            ./circleci_tests.sh


workflows:
  version: 0.4
  melodic_py3:
    jobs:
      - melodic_install_ubuntu_18
